name: etam-course

services:
  postgres:
    image: postgres:12.20-alpine3.20
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: S3cret
      POSTGRES_USER: etamcourse_user
      POSTGRES_DB: etamcourse_db
