import { prisma } from "../../application/database";

export const contentSeeder = async () => {
  await prisma.content.createMany({
    data: [
      // Chapter 1: Introduction to React Native
      {
        id: 1,
        sort: 1,
        chapterId: 1,
        contentTitle: "What is React Native?",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 300,
        teks: "Video ini menjelaskan konsep dasar React Native sebagai framework open-source yang dikembangkan oleh Facebook. Anda akan mempelajari bagaimana React Native memungkinkan pengembang untuk membuat aplikasi mobile lintas platform menggunakan JavaScript dan React. Selain itu, video ini menguraikan perbedaan mendasar antara aplikasi native dan aplikasi hybrid, serta keuntungan yang didapat saat menggunakan React Native, seperti kinerja yang mendekati aplikasi native dan kemampuan untuk menggunakan kembali kode di berbagai platform.",
        interpreterId: null,
        interpreterStatus: false,
      },
      {
        id: 2,
        sort: 2,
        chapterId: 1,
        contentTitle: "Overview of React Native Components",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 400,
        teks: "Di video ini, Anda akan mendapatkan pemahaman yang lebih dalam tentang berbagai komponen yang tersedia di React Native, termasuk komponen dasar seperti View, Text, dan Image. Video ini juga mencakup cara menggunakan komponen-komponen ini untuk membangun antarmuka pengguna yang menarik dan interaktif. Anda juga akan belajar tentang props, yang merupakan cara untuk mengirim data ke komponen dan menyesuaikan tampilannya sesuai kebutuhan.",
        interpreterId: null,
        interpreterStatus: false,
      },

      // Chapter 2: Setting Up the Environment
      {
        id: 3,
        sort: 1,
        chapterId: 2,
        contentTitle: "Installing Node.js and React Native CLI",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 250,
        teks: "Video ini memberikan panduan langkah demi langkah tentang cara menginstal Node.js, yang merupakan runtime JavaScript yang diperlukan untuk menjalankan React Native. Selanjutnya, Anda akan mempelajari cara menginstal React Native CLI, alat yang memudahkan dalam membuat dan mengelola proyek React Native. Video ini juga menjelaskan pengaturan PATH pada sistem Anda agar dapat menjalankan perintah React Native dari terminal.",
        interpreterId: null,
        interpreterStatus: false,
      },
      {
        id: 4,
        sort: 2,
        chapterId: 2,
        contentTitle: "Setting Up Android Studio and Emulator",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 300,
        teks: "Di video ini, Anda akan belajar cara mengatur Android Studio, yang merupakan lingkungan pengembangan yang diperlukan untuk mengembangkan aplikasi Android dengan React Native. Anda akan mengikuti langkah-langkah untuk mengunduh dan menginstal Android Studio, serta mengonfigurasi emulator untuk menguji aplikasi Anda. Penjelasan tentang cara membuat Virtual Device dan menjalankannya akan sangat membantu saat Anda ingin melihat bagaimana aplikasi berfungsi di perangkat Android.",
        interpreterId: null,
        interpreterStatus: false,
      },

      // Chapter 3: Creating Your First App
      {
        id: 5,
        sort: 1,
        chapterId: 3,
        contentTitle: "Creating a New React Native Project",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 350,
        teks: "Video ini membimbing Anda melalui proses membuat proyek baru dengan React Native menggunakan React Native CLI. Anda akan melihat struktur dasar proyek yang dihasilkan, termasuk file utama yang perlu Anda ketahui, seperti App.js. Selain itu, video ini akan menjelaskan bagaimana cara memodifikasi komponen pertama Anda dan melihat perubahan langsung menggunakan hot reloading, yang memungkinkan pengembang untuk melihat hasil perubahan kode secara instan.",
        interpreterId: null,
        interpreterStatus: false,
      },
      {
        id: 6,
        sort: 2,
        chapterId: 3,
        contentTitle: "Running Your First App",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 300,
        teks: "Di sini, Anda akan belajar cara menjalankan aplikasi React Native pertama Anda di emulator Android atau perangkat fisik. Video ini menjelaskan perintah yang digunakan untuk menjalankan aplikasi, termasuk 'react-native run-android' atau 'react-native run-ios'. Anda juga akan diperkenalkan dengan alat pengembangan yang dapat membantu dalam proses debugging dan pengujian aplikasi.",
        interpreterId: null,
        interpreterStatus: false,
      },

      // Chapter 4: Understanding Components
      {
        id: 7,
        sort: 1,
        chapterId: 4,
        contentTitle: "Class vs Functional Components",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 400,
        teks: "Video ini membahas perbedaan antara komponen kelas dan komponen fungsional di React Native. Anda akan mempelajari keuntungan dan kerugian dari masing-masing jenis komponen, serta kapan harus menggunakannya. Selain itu, penjelasan tentang hooks, yang memungkinkan penggunaan state dan lifecycle di komponen fungsional, juga menjadi bagian penting dari video ini.",
        interpreterId: null,
        interpreterStatus: false,
      },
      {
        id: 8,
        sort: 2,
        chapterId: 4,
        contentTitle: "Props and State in Components",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 300,
        teks: "Di sini, Anda akan belajar tentang props dan state, dua konsep inti yang memungkinkan komponen React Native berfungsi dengan baik. Video ini menjelaskan cara mengirim data ke komponen menggunakan props dan bagaimana mengelola state lokal dalam komponen. Anda juga akan melihat contoh nyata penggunaan props dan state dalam membangun UI dinamis.",
        interpreterId: null,
        interpreterStatus: false,
      },

      // Chapter 5: Styling in React Native
      {
        id: 9,
        sort: 1,
        chapterId: 5,
        contentTitle: "Using Stylesheets",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 350,
        teks: "Video ini memberikan panduan tentang cara menggunakan stylesheet untuk memberikan gaya pada komponen di React Native. Anda akan belajar bagaimana mendefinisikan gaya menggunakan objek dan kemudian menerapkannya ke komponen. Penjelasan tentang properti styling dasar seperti margin, padding, dan color akan membuat Anda memahami bagaimana mengatur layout dan estetika aplikasi.",
        interpreterId: null,
        interpreterStatus: false,
      },
      {
        id: 10,
        sort: 2,
        chapterId: 5,
        contentTitle: "Flexbox Layout in React Native",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 300,
        teks: "Di sini, Anda akan belajar tentang penggunaan Flexbox untuk membuat tata letak responsif di aplikasi React Native. Video ini menjelaskan konsep dasar Flexbox, seperti flexDirection, justifyContent, dan alignItems, serta bagaimana menerapkannya untuk mencapai tata letak yang diinginkan. Contoh kode praktis akan membantu Anda melihat bagaimana Flexbox dapat digunakan untuk membangun antarmuka pengguna yang menarik dan fungsional.",
        interpreterId: null,
        interpreterStatus: false,
      },

      // Chapter 6: Managing State
      {
        id: 11,
        sort: 1,
        chapterId: 6,
        contentTitle: "State Management Basics",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 300,
        teks: "Video ini memperkenalkan konsep manajemen state dalam React Native, menjelaskan pentingnya state untuk aplikasi yang interaktif. Anda akan belajar tentang hook useState, yang memungkinkan Anda mendeklarasikan state dalam komponen fungsional. Selain itu, penjelasan tentang lifecycle components dan bagaimana perubahan state dapat mempengaruhi UI akan memberikan pemahaman yang lebih dalam tentang bagaimana React bekerja.",
        interpreterId: null,
        interpreterStatus: false,
      },
      {
        id: 12,
        sort: 2,
        chapterId: 6,
        contentTitle: "Using Context API for State Management",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 400,
        teks: "Di video ini, Anda akan mempelajari cara menggunakan Context API untuk mengelola state global di aplikasi React Native. Anda akan belajar cara membuat Context, menyediakan nilai, dan menggunakan useContext untuk mengakses nilai tersebut di komponen anak. Penjelasan ini penting untuk pengembangan aplikasi besar di mana state harus diakses oleh banyak komponen tanpa harus mengoper props secara berlapis-lapis.",
        interpreterId: null,
        interpreterStatus: false,
      },

      // Chapter 7: Navigation in React Native
      {
        id: 13,
        sort: 1,
        chapterId: 7,
        contentTitle: "Setting Up React Navigation",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 300,
        teks: "Video ini mengajarkan cara menginstal dan mengkonfigurasi React Navigation, library yang memungkinkan navigasi antar layar di aplikasi React Native. Anda akan belajar tentang berbagai jenis navigator, termasuk Stack Navigator dan Tab Navigator, serta cara menambahkan navigasi ke aplikasi Anda dengan mudah.",
        interpreterId: null,
        interpreterStatus: false,
      },
      {
        id: 14,
        sort: 2,
        chapterId: 7,
        contentTitle: "Stack Navigation Example",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 400,
        teks: "Dalam video ini, Anda akan melihat contoh konkret penggunaan Stack Navigation untuk berpindah antara dua layar dalam aplikasi. Penjelasan tentang cara menambahkan tombol navigasi dan menangani navigasi kembali akan membantu Anda memahami bagaimana cara aplikasi bekerja secara dinamis saat pengguna berinteraksi dengan antarmuka.",
        interpreterId: null,
        interpreterStatus: false,
      },

      // Chapter 8: Working with APIs
      {
        id: 15,
        sort: 1,
        chapterId: 8,
        contentTitle: "Fetching Data from APIs",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 350,
        teks: "Video ini menjelaskan cara mengambil data dari API menggunakan metode fetch dalam React Native. Anda akan belajar bagaimana membuat permintaan GET ke API, menangani respons JSON, dan menangani kesalahan dengan benar. Penjelasan ini sangat penting bagi pengembang yang ingin mengintegrasikan data eksternal ke dalam aplikasi mereka.",
        interpreterId: null,
        interpreterStatus: false,
      },
      {
        id: 16,
        sort: 2,
        chapterId: 8,
        contentTitle: "Displaying API Data in Components",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 300,
        teks: "Di sini, Anda akan belajar cara menampilkan data yang diambil dari API ke dalam komponen React Native. Video ini mencakup penggunaan komponen FlatList untuk menampilkan daftar data secara efisien, serta cara mengelola state untuk menyimpan data yang diambil. Contoh nyata akan membantu Anda memahami bagaimana menyusun data dan menampilkannya secara dinamis di UI.",
        interpreterId: null,
        interpreterStatus: false,
      },

      // Chapter 9: Publishing Your App
      {
        id: 17,
        sort: 1,
        chapterId: 9,
        contentTitle: "Preparing Your App for Publishing",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 400,
        teks: "Video ini menjelaskan langkah-langkah yang diperlukan untuk menyiapkan aplikasi React Native Anda agar siap dipublikasikan di App Store dan Google Play Store. Anda akan belajar tentang pengaturan build, pembuatan file APK untuk Android, dan cara menyiapkan file untuk distribusi di iOS. Selain itu, panduan ini juga mencakup informasi tentang sertifikat yang diperlukan dan proses submit aplikasi ke toko aplikasi.",
        interpreterId: null,
        interpreterStatus: false,
      },
      {
        id: 18,
        sort: 2,
        chapterId: 9,
        contentTitle: "Final Testing and Submission",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 300,
        teks: "Dalam video ini, Anda akan mendapatkan panduan tentang pengujian terakhir yang harus dilakukan sebelum mengirimkan aplikasi Anda. Video ini mencakup tips untuk memastikan bahwa aplikasi Anda memenuhi semua persyaratan dari App Store dan Google Play Store, serta cara memeriksa bug dan performa aplikasi. Anda juga akan belajar tentang proses submit aplikasi secara praktis dan apa yang diharapkan setelah pengiriman.",
        interpreterId: null,
        interpreterStatus: false,
      },
      // Chapter 10: Advanced Components
      {
        id: 19,
        sort: 1,
        chapterId: 10,
        contentTitle: "Creating Custom Components",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 400,
        teks: "Video ini membahas cara membuat komponen kustom di React Native. Anda akan belajar bagaimana mengorganisir kode Anda dengan baik, membuat komponen reusable yang dapat digunakan di berbagai bagian aplikasi Anda. Selain itu, Anda juga akan mempelajari bagaimana mengelola props dan state di dalam komponen kustom Anda untuk meningkatkan fleksibilitas dan efisiensi.",
        interpreterId: null,
        interpreterStatus: false,
      },
      {
        id: 20,
        sort: 2,
        chapterId: 10,
        contentTitle: "Using Third-Party Libraries",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 350,
        teks: "Di video ini, Anda akan diperkenalkan dengan berbagai library pihak ketiga yang dapat digunakan untuk meningkatkan fungsionalitas aplikasi React Native Anda. Anda akan belajar cara menginstal dan mengintegrasikan library seperti React Native Elements dan React Native Vector Icons untuk memperkaya antarmuka pengguna dan menambahkan ikon ke aplikasi Anda.",
        interpreterId: null,
        interpreterStatus: false,
      },

      // Chapter 11: Handling User Input
      {
        id: 21,
        sort: 1,
        chapterId: 11,
        contentTitle: "Working with TextInput",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 300,
        teks: "Video ini menjelaskan cara menggunakan komponen TextInput untuk menangani input teks dari pengguna. Anda akan belajar cara mengonfigurasi TextInput untuk menerima berbagai jenis input, seperti email, password, dan lainnya. Penjelasan tentang cara mengelola state untuk menyimpan input pengguna juga menjadi fokus utama di video ini.",
        interpreterId: null,
        interpreterStatus: false,
      },
      {
        id: 22,
        sort: 2,
        chapterId: 11,
        contentTitle: "Handling Forms in React Native",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 350,
        teks: "Di sini, Anda akan belajar cara menangani form di React Native menggunakan komponen TextInput dan Button. Video ini mencakup bagaimana mengelola state form dan melakukan validasi input sebelum mengirim data ke server. Anda juga akan mendapatkan pemahaman tentang cara membuat UI form yang ramah pengguna.",
        interpreterId: null,
        interpreterStatus: false,
      },

      // Chapter 12: Debugging Techniques
      {
        id: 23,
        sort: 1,
        chapterId: 12,
        contentTitle: "Debugging with Console and Alerts",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 300,
        teks: "Video ini menjelaskan teknik dasar debugging di React Native menggunakan console.log dan alert. Anda akan belajar cara melacak kesalahan dan memahami alur data dalam aplikasi Anda. Selain itu, penjelasan tentang cara menggunakan DevTools untuk meningkatkan proses debugging juga akan menjadi bagian penting dari video ini.",
        interpreterId: null,
        interpreterStatus: false,
      },
      {
        id: 24,
        sort: 2,
        chapterId: 12,
        contentTitle: "Using React Developer Tools",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 350,
        teks: "Di video ini, Anda akan diperkenalkan dengan React Developer Tools, alat yang sangat berguna untuk menganalisis dan debug aplikasi React Native. Anda akan belajar bagaimana menggunakan alat ini untuk memeriksa komponen, props, dan state aplikasi Anda, serta cara memperbaiki masalah dengan cepat.",
        interpreterId: null,
        interpreterStatus: false,
      },

      // Chapter 13: Performance Optimization
      {
        id: 25,
        sort: 1,
        chapterId: 13,
        contentTitle: "Improving App Performance",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 300,
        teks: "Video ini membahas teknik untuk meningkatkan performa aplikasi React Native. Anda akan belajar tentang cara meminimalkan waktu loading, penggunaan image yang efisien, dan bagaimana mengoptimalkan komponen agar tidak melakukan rendering berulang yang tidak perlu. Penjelasan ini akan sangat membantu untuk memastikan aplikasi Anda berjalan lancar.",
        interpreterId: null,
        interpreterStatus: false,
      },
      {
        id: 26,
        sort: 2,
        chapterId: 13,
        contentTitle: "Using React.memo and PureComponent",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 350,
        teks: "Di sini, Anda akan mempelajari bagaimana menggunakan React.memo dan PureComponent untuk meningkatkan performa aplikasi Anda dengan cara mencegah re-rendering komponen yang tidak perlu. Video ini menjelaskan cara kerja kedua teknik ini dan kapan sebaiknya Anda menggunakannya.",
        interpreterId: null,
        interpreterStatus: false,
      },

      // Chapter 14: Animations
      {
        id: 27,
        sort: 1,
        chapterId: 14,
        contentTitle: "Animating Components with Animated API",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 400,
        teks: "Video ini memberikan penjelasan tentang cara menggunakan Animated API untuk menambahkan animasi pada komponen React Native. Anda akan belajar tentang berbagai jenis animasi, seperti fade, slide, dan scale, serta cara menerapkannya untuk meningkatkan pengalaman pengguna. Contoh praktis akan membantu Anda memahami cara kerja Animated API dengan lebih baik.",
        interpreterId: null,
        interpreterStatus: false,
      },
      {
        id: 28,
        sort: 2,
        chapterId: 14,
        contentTitle: "Using LayoutAnimation for Transitions",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 350,
        teks: "Di sini, Anda akan belajar tentang LayoutAnimation dan cara menggunakannya untuk membuat transisi yang halus saat mengubah layout komponen. Video ini mencakup bagaimana mengonfigurasi animasi dan cara mengoptimalkan performa animasi agar tetap responsif dan menarik.",
        interpreterId: null,
        interpreterStatus: false,
      },

      // Chapter 15: Networking and Offline Capabilities
      {
        id: 29,
        sort: 1,
        chapterId: 15,
        contentTitle: "Handling Network Requests",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 300,
        teks: "Video ini menjelaskan cara menangani permintaan jaringan menggunakan Fetch API di React Native. Anda akan belajar tentang cara menangani respons dari server, termasuk menangani kesalahan yang mungkin terjadi. Penjelasan tentang cara kerja asynchronous JavaScript juga akan membantu Anda memahami pengelolaan permintaan jaringan dengan lebih baik.",
        interpreterId: null,
        interpreterStatus: false,
      },
      {
        id: 30,
        sort: 2,
        chapterId: 15,
        contentTitle: "Implementing Offline Storage",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 350,
        teks: "Di video ini, Anda akan belajar bagaimana mengimplementasikan penyimpanan offline menggunakan AsyncStorage di React Native. Anda akan belajar cara menyimpan dan mengambil data dari penyimpanan lokal, serta cara menangani situasi ketika aplikasi tidak memiliki koneksi internet. Penjelasan ini sangat penting bagi aplikasi yang memerlukan akses data yang konsisten meskipun dalam kondisi offline.",
        interpreterId: null,
        interpreterStatus: false,
      },

      // Chapter 16: User Authentication
      {
        id: 31,
        sort: 1,
        chapterId: 16,
        contentTitle: "Implementing User Authentication",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 400,
        teks: "Video ini menjelaskan bagaimana cara mengimplementasikan sistem autentikasi pengguna di aplikasi React Native. Anda akan belajar tentang metode autentikasi seperti menggunakan token JWT dan menghubungkan aplikasi Anda dengan backend untuk memverifikasi pengguna. Penjelasan ini mencakup cara menangani sesi pengguna dan cara mengamankan data sensitif.",
        interpreterId: null,
        interpreterStatus: false,
      },
      {
        id: 32,
        sort: 2,
        chapterId: 16,
        contentTitle: "Social Media Authentication",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 350,
        teks: "Di sini, Anda akan belajar cara mengintegrasikan autentikasi melalui media sosial seperti Facebook dan Google di aplikasi React Native Anda. Video ini mencakup pengaturan API yang diperlukan dan langkah-langkah untuk menangani autentikasi pengguna dengan menggunakan SDK dari masing-masing platform.",
        interpreterId: null,
        interpreterStatus: false,
      },

      // Chapter 17: State Management
      {
        id: 33,
        sort: 1,
        chapterId: 17,
        contentTitle: "Introduction to State Management",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 300,
        teks: "Video ini memberikan pengantar tentang manajemen state di aplikasi React Native. Anda akan belajar tentang pentingnya pengelolaan state dalam aplikasi berskala besar dan bagaimana memanfaatkan state management libraries seperti Redux untuk mengelola state aplikasi Anda secara efisien.",
        interpreterId: null,
        interpreterStatus: false,
      },
      {
        id: 34,
        sort: 2,
        chapterId: 17,
        contentTitle: "Using Redux for State Management",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 400,
        teks: "Di video ini, Anda akan mendapatkan panduan lengkap tentang cara mengintegrasikan Redux ke dalam aplikasi React Native Anda. Anda akan belajar tentang konsep dasar Redux seperti store, actions, dan reducers, serta bagaimana menghubungkan Redux dengan komponen React untuk pengelolaan state yang lebih terstruktur.",
        interpreterId: null,
        interpreterStatus: false,
      },

      // Chapter 18: Deployment and Maintenance
      {
        id: 35,
        sort: 1,
        chapterId: 18,
        contentTitle: "Preparing Your App for Production",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 400,
        teks: "Video ini menjelaskan langkah-langkah yang diperlukan untuk menyiapkan aplikasi React Native Anda agar siap untuk produksi. Anda akan belajar tentang optimasi yang harus dilakukan, seperti minifikasi kode dan penghapusan dependensi yang tidak diperlukan, serta cara mengkonfigurasi environment variabel untuk produksi.",
        interpreterId: null,
        interpreterStatus: false,
      },
      {
        id: 36,
        sort: 2,
        chapterId: 18,
        contentTitle: "Monitoring and Updating Your App",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 350,
        teks: "Di sini, Anda akan belajar tentang pentingnya memantau performa aplikasi setelah dirilis. Video ini mencakup cara menggunakan alat analitik untuk melacak penggunaan aplikasi dan bagaimana merilis pembaruan untuk meningkatkan pengalaman pengguna berdasarkan umpan balik. Anda juga akan mendapatkan tips untuk mengelola rilis dan meminimalkan gangguan bagi pengguna.",
        interpreterId: null,
        interpreterStatus: false,
      },

      // Chapter 19: Testing
      {
        id: 37,
        sort: 1,
        chapterId: 19,
        contentTitle: "Writing Unit Tests for Components",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 400,
        teks: "Video ini menjelaskan pentingnya pengujian unit dalam pengembangan aplikasi dan bagaimana cara menulis pengujian untuk komponen React Native menggunakan Jest. Anda akan belajar cara mengatur lingkungan pengujian dan menulis tes untuk memastikan bahwa komponen Anda berfungsi dengan benar.",
        interpreterId: null,
        interpreterStatus: false,
      },
      {
        id: 38,
        sort: 2,
        chapterId: 19,
        contentTitle: "End-to-End Testing with Detox",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 350,
        teks: "Di video ini, Anda akan belajar tentang pengujian end-to-end menggunakan Detox. Video ini mencakup bagaimana cara menyiapkan Detox dalam proyek Anda, menulis tes untuk berbagai skenario pengguna, dan memastikan bahwa aplikasi Anda berfungsi dengan baik dari awal hingga akhir.",
        interpreterId: null,
        interpreterStatus: false,
      },

      // Chapter 20: Best Practices
      {
        id: 39,
        sort: 1,
        chapterId: 20,
        contentTitle: "Code Organization and Best Practices",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 400,
        teks: "Video ini memberikan panduan tentang praktik terbaik dalam mengorganisir kode aplikasi React Native. Anda akan belajar tentang struktur folder yang efisien, penggunaan komponen dengan cara yang modular, dan tips untuk menjaga kode Anda tetap bersih dan mudah dipelihara.",
        interpreterId: null,
        interpreterStatus: false,
      },
      {
        id: 40,
        sort: 2,
        chapterId: 20,
        contentTitle: "Performance Optimization Techniques",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 350,
        teks: "Di sini, Anda akan belajar tentang teknik-teknik lanjutan untuk mengoptimalkan performa aplikasi React Native Anda. Video ini mencakup penggunaan memoization, pengurangan re-render, dan pengelolaan sumber daya yang efisien untuk memastikan aplikasi Anda responsif dan cepat.",
        interpreterId: null,
        interpreterStatus: false,
      },

      // Chapter 21: Advanced Topics
      {
        id: 41,
        sort: 1,
        chapterId: 21,
        contentTitle: "Using Native Modules",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 400,
        teks: "Video ini membahas bagaimana cara menggunakan modul native dalam aplikasi React Native Anda. Anda akan belajar tentang cara menulis kode native untuk iOS dan Android serta cara menghubungkannya dengan JavaScript untuk memanfaatkan fungsionalitas perangkat yang lebih dalam.",
        interpreterId: null,
        interpreterStatus: false,
      },
      {
        id: 42,
        sort: 2,
        chapterId: 21,
        contentTitle: "Integrating with Existing Native Apps",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 350,
        teks: "Di sini, Anda akan belajar tentang cara mengintegrasikan aplikasi React Native dengan aplikasi native yang sudah ada. Video ini mencakup langkah-langkah untuk menghubungkan kedua aplikasi dan cara berkomunikasi antara JavaScript dan kode native untuk memanfaatkan fungsionalitas yang sudah ada.",
        interpreterId: null,
        interpreterStatus: false,
      },

      // Chapter 22: Working with Device Features
      {
        id: 43,
        sort: 1,
        chapterId: 22,
        contentTitle: "Accessing Device Camera",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 400,
        teks: "Video ini menjelaskan bagaimana cara mengakses kamera perangkat menggunakan library seperti react-native-camera. Anda akan belajar tentang cara mengambil foto, merekam video, dan menangani izin yang diperlukan untuk menggunakan fitur kamera.",
        interpreterId: null,
        interpreterStatus: false,
      },
      {
        id: 44,
        sort: 2,
        chapterId: 22,
        contentTitle: "Using Geolocation",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 350,
        teks: "Di video ini, Anda akan belajar tentang cara menggunakan fitur geolokasi di React Native untuk mendapatkan lokasi pengguna. Anda akan memahami bagaimana cara menangani izin, mendapatkan lokasi saat ini, dan memperbarui lokasi pengguna secara real-time.",
        interpreterId: null,
        interpreterStatus: false,
      },

      // Chapter 23: Internationalization and Localization
      {
        id: 45,
        sort: 1,
        chapterId: 23,
        contentTitle: "Introduction to Internationalization",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 400,
        teks: "Video ini menjelaskan dasar-dasar internasionalisasi dalam aplikasi React Native. Anda akan belajar tentang pentingnya mendukung berbagai bahasa dan cara mengelola teks dan konten yang dapat diterjemahkan menggunakan library seperti react-i18next.",
        interpreterId: null,
        interpreterStatus: false,
      },
      {
        id: 46,
        sort: 2,
        chapterId: 23,
        contentTitle: "Implementing Localization",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 350,
        teks: "Di sini, Anda akan belajar cara mengimplementasikan lokalizasi dalam aplikasi React Native Anda. Video ini mencakup cara mengatur file bahasa, menerjemahkan teks, dan menyesuaikan konten berdasarkan preferensi pengguna. Anda juga akan belajar cara mendeteksi dan beradaptasi dengan bahasa perangkat pengguna.",
        interpreterId: null,
        interpreterStatus: false,
      },

      // Chapter 24: Understanding React Native Ecosystem
      {
        id: 47,
        sort: 1,
        chapterId: 24,
        contentTitle: "Overview of React Native Ecosystem",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 400,
        teks: "Video ini memberikan gambaran umum tentang ekosistem React Native, termasuk berbagai alat, library, dan komunitas yang tersedia untuk pengembang. Anda akan memahami cara menggunakan alat pengembangan, melakukan debugging, dan menemukan sumber daya yang dapat membantu Anda dalam pengembangan aplikasi.",
        interpreterId: null,
        interpreterStatus: false,
      },
      {
        id: 48,
        sort: 2,
        chapterId: 24,
        contentTitle: "Joining the React Native Community",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 350,
        teks: "Di sini, Anda akan belajar tentang pentingnya bergabung dengan komunitas React Native untuk mendapatkan dukungan dan sumber daya tambahan. Video ini mencakup cara terlibat dalam forum, grup media sosial, dan acara lokal untuk berkolaborasi dengan pengembang lain dan meningkatkan keterampilan Anda.",
        interpreterId: null,
        interpreterStatus: false,
      },

      // Chapter 25: Future of React Native
      {
        id: 49,
        sort: 1,
        chapterId: 25,
        contentTitle: "What’s Next for React Native",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 400,
        teks: "Video ini membahas arah masa depan React Native, termasuk fitur dan pembaruan yang diharapkan. Anda akan belajar tentang komunitas yang berkembang, inisiatif open-source, dan bagaimana React Native beradaptasi dengan kebutuhan industri pengembangan aplikasi yang terus berubah.",
        interpreterId: null,
        interpreterStatus: false,
      },
      {
        id: 50,
        sort: 2,
        chapterId: 25,
        contentTitle: "Building a Career with React Native",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 350,
        teks: "Di sini, Anda akan belajar tentang cara membangun karir Anda sebagai pengembang React Native. Video ini mencakup tips untuk mencari pekerjaan, membangun portofolio, dan cara terus meningkatkan keterampilan Anda untuk tetap relevan di industri teknologi.",
        interpreterId: null,
        interpreterStatus: false,
      },

      // Chapter 26: Project Showcase
      {
        id: 51,
        sort: 1,
        chapterId: 26,
        contentTitle: "Showcasing Real-World Projects",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 400,
        teks: "Video ini menampilkan berbagai proyek dunia nyata yang dibangun menggunakan React Native. Anda akan mendapatkan inspirasi dan wawasan tentang bagaimana aplikasi-aplikasi ini dirancang, tantangan yang dihadapi, dan solusi yang diterapkan untuk mencapai hasil yang sukses.",
        interpreterId: null,
        interpreterStatus: false,
      },
      {
        id: 52,
        sort: 2,
        chapterId: 26,
        contentTitle: "Case Studies and Lessons Learned",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 350,
        teks: "Di sini, Anda akan belajar dari studi kasus berbagai aplikasi yang telah sukses. Video ini membahas tantangan yang dihadapi dalam proses pengembangan, keputusan desain yang diambil, dan pelajaran yang bisa dipelajari untuk meningkatkan proyek Anda sendiri.",
        interpreterId: null,
        interpreterStatus: false,
      },

      // Chapter 27: Conclusion
      {
        id: 53,
        sort: 1,
        chapterId: 27,
        contentTitle: "Recap of Key Concepts",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 400,
        teks: "Video ini memberikan ringkasan dari semua konsep kunci yang telah dibahas selama kursus. Anda akan mendapatkan gambaran umum tentang apa yang telah dipelajari dan bagaimana menerapkannya dalam proyek React Native Anda sendiri.",
        interpreterId: null,
        interpreterStatus: false,
      },
      {
        id: 54,
        sort: 2,
        chapterId: 27,
        contentTitle: "Next Steps and Resources",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 350,
        teks: "Di sini, Anda akan mendapatkan rekomendasi untuk langkah selanjutnya setelah menyelesaikan kursus ini. Video ini mencakup sumber daya tambahan untuk belajar lebih lanjut, proyek yang dapat Anda kerjakan, dan bagaimana cara terus berkontribusi pada komunitas React Native.",
        interpreterId: null,
        interpreterStatus: false,
      },
      // Chapter 28: Advanced Performance Techniques
      {
        id: 55,
        sort: 1,
        chapterId: 28,
        contentTitle: "Profiling and Monitoring Performance",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 400,
        teks: "Video ini membahas cara menggunakan alat profiling untuk memantau performa aplikasi React Native Anda. Anda akan belajar bagaimana cara menganalisis penggunaan memori, waktu render, dan pengoptimalan untuk meningkatkan responsivitas aplikasi.",
        interpreterId: null,
        interpreterStatus: false,
      },
      {
        id: 56,
        sort: 2,
        chapterId: 28,
        contentTitle: "Optimizing for Mobile Devices",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 350,
        teks: "Di sini, Anda akan mendapatkan tips dan trik untuk mengoptimalkan aplikasi React Native agar berjalan dengan baik di perangkat mobile dengan spesifikasi rendah. Video ini mencakup teknik seperti pengurangan ukuran aset dan penggunaan gambar dengan resolusi yang tepat.",
        interpreterId: null,
        interpreterStatus: false,
      },

      // Chapter 29: Security Best Practices
      {
        id: 57,
        sort: 1,
        chapterId: 29,
        contentTitle: "Understanding Security Risks",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 400,
        teks: "Video ini menjelaskan berbagai risiko keamanan yang mungkin dihadapi oleh aplikasi React Native. Anda akan belajar tentang praktik terbaik untuk melindungi data pengguna dan mencegah potensi serangan, termasuk XSS dan serangan injeksi.",
        interpreterId: null,
        interpreterStatus: false,
      },
      {
        id: 58,
        sort: 2,
        chapterId: 29,
        contentTitle: "Implementing Secure Storage",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 350,
        teks: "Di video ini, Anda akan belajar cara mengimplementasikan penyimpanan yang aman untuk data sensitif dalam aplikasi React Native menggunakan library seperti SecureStore. Anda akan memahami cara menangani kredensial dan informasi pengguna dengan aman.",
        interpreterId: null,
        interpreterStatus: false,
      },

      // Chapter 30: Future Trends and Innovations
      {
        id: 59,
        sort: 1,
        chapterId: 30,
        contentTitle: "Emerging Trends in Mobile Development",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 400,
        teks: "Video ini membahas tren yang sedang muncul dalam pengembangan aplikasi mobile, termasuk perkembangan teknologi baru dan bagaimana hal ini mempengaruhi React Native. Anda akan belajar tentang integrasi AI dan pembelajaran mesin dalam aplikasi mobile.",
        interpreterId: null,
        interpreterStatus: false,
      },
      {
        id: 60,
        sort: 2,
        chapterId: 30,
        contentTitle: "Preparing for Future Challenges",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 350,
        teks: "Di sini, Anda akan mendapatkan wawasan tentang tantangan yang mungkin dihadapi dalam pengembangan aplikasi di masa depan dan bagaimana cara mengatasinya. Video ini mencakup strategi untuk tetap relevan dan adaptif terhadap perubahan teknologi dan kebutuhan pasar.",
        interpreterId: null,
        interpreterStatus: false,
      },
      // Chapter 31: Introduction to Machine Learning
      {
        id: 61,
        sort: 1,
        chapterId: 31,
        contentTitle: "What is Machine Learning?",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 300,
        teks: "Video ini memberikan pengantar tentang konsep dasar machine learning, menjelaskan apa itu machine learning dan bagaimana cara kerjanya. Anda juga akan belajar tentang perbedaan antara supervised, unsupervised, dan reinforcement learning.",
        interpreterId: null,
        interpreterStatus: false,
      },
      {
        id: 62,
        sort: 2,
        chapterId: 31,
        contentTitle: "Applications of Machine Learning",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 350,
        teks: "Dalam video ini, berbagai aplikasi machine learning di berbagai industri dibahas, termasuk di bidang kesehatan, keuangan, dan transportasi. Anda akan memahami bagaimana machine learning dapat meningkatkan efisiensi dan produktivitas.",
        interpreterId: null,
        interpreterStatus: false,
      },

      // Chapter 32: Types of Machine Learning
      {
        id: 63,
        sort: 1,
        chapterId: 32,
        contentTitle: "Supervised Learning",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 300,
        teks: "Video ini membahas tentang supervised learning, di mana model dilatih dengan data berlabel. Anda akan belajar tentang algoritma yang digunakan dan bagaimana cara menyiapkan dataset untuk pelatihan.",
        interpreterId: null,
        interpreterStatus: false,
      },
      {
        id: 64,
        sort: 2,
        chapterId: 32,
        contentTitle: "Unsupervised Learning",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 350,
        teks: "Di sini, Anda akan mendapatkan penjelasan mengenai unsupervised learning, di mana model belajar dari data yang tidak berlabel. Video ini mencakup teknik seperti clustering dan dimensionality reduction.",
        interpreterId: null,
        interpreterStatus: false,
      },

      // Chapter 33: Data Preprocessing
      {
        id: 65,
        sort: 1,
        chapterId: 33,
        contentTitle: "Importance of Data Preprocessing",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 300,
        teks: "Video ini menjelaskan mengapa preprocessing data sangat penting dalam machine learning. Anda akan belajar tentang langkah-langkah seperti penghapusan data yang hilang, normalisasi, dan encoding fitur.",
        interpreterId: null,
        interpreterStatus: false,
      },
      {
        id: 66,
        sort: 2,
        chapterId: 33,
        contentTitle: "Feature Engineering",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 350,
        teks: "Di video ini, teknik-teknik feature engineering yang efektif dijelaskan. Anda akan belajar bagaimana cara memilih dan membuat fitur yang relevan untuk meningkatkan akurasi model.",
        interpreterId: null,
        interpreterStatus: false,
      },

      // Chapter 34: Regression Algorithms
      {
        id: 67,
        sort: 1,
        chapterId: 34,
        contentTitle: "Linear Regression",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 300,
        teks: "Video ini membahas tentang linear regression, salah satu algoritma yang paling sederhana dan umum digunakan. Anda akan belajar bagaimana membangun model regresi dan mengevaluasi performanya.",
        interpreterId: null,
        interpreterStatus: false,
      },
      {
        id: 68,
        sort: 2,
        chapterId: 34,
        contentTitle: "Polynomial Regression",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 350,
        teks: "Dalam video ini, Anda akan belajar tentang polynomial regression yang memungkinkan model untuk menangkap hubungan non-linear. Contoh implementasi dan evaluasi performa juga dibahas.",
        interpreterId: null,
        interpreterStatus: false,
      },

      // Chapter 35: Classification Algorithms
      {
        id: 69,
        sort: 1,
        chapterId: 35,
        contentTitle: "Introduction to Classification",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 300,
        teks: "Video ini menjelaskan apa itu algoritma klasifikasi dan bagaimana mereka digunakan untuk memprediksi kategori. Anda akan diperkenalkan pada konsep dasar dan contoh aplikasi.",
        interpreterId: null,
        interpreterStatus: false,
      },
      {
        id: 70,
        sort: 2,
        chapterId: 35,
        contentTitle: "Decision Trees",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 350,
        teks: "Di sini, Anda akan belajar tentang decision trees, salah satu algoritma klasifikasi yang paling populer. Video ini mencakup cara membangun dan memvisualisasikan pohon keputusan.",
        interpreterId: null,
        interpreterStatus: false,
      },

      // Chapter 36: Model Evaluation
      {
        id: 71,
        sort: 1,
        chapterId: 36,
        contentTitle: "Understanding Evaluation Metrics",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 300,
        teks: "Video ini membahas berbagai metrik evaluasi yang digunakan untuk mengukur performa model machine learning. Anda akan belajar tentang akurasi, precision, recall, dan F1-score.",
        interpreterId: null,
        interpreterStatus: false,
      },
      {
        id: 72,
        sort: 2,
        chapterId: 36,
        contentTitle: "Cross-Validation Techniques",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 350,
        teks: "Dalam video ini, Anda akan belajar tentang teknik cross-validation untuk mengevaluasi model. Ini termasuk pembagian data menjadi subset dan cara menggunakan k-fold cross-validation.",
        interpreterId: null,
        interpreterStatus: false,
      },

      // Chapter 37: Building ML Projects
      {
        id: 73,
        sort: 1,
        chapterId: 37,
        contentTitle: "End-to-End Machine Learning Project",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 300,
        teks: "Video ini mengilustrasikan proses membangun proyek machine learning dari awal hingga akhir. Anda akan melihat langkah-langkah mulai dari pemilihan dataset hingga penerapan model.",
        interpreterId: null,
        interpreterStatus: false,
      },
      {
        id: 74,
        sort: 2,
        chapterId: 37,
        contentTitle: "Deploying Machine Learning Models",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 350,
        teks: "Di sini, Anda akan belajar tentang cara menerapkan model machine learning dalam lingkungan produksi. Proses ini mencakup pembuatan API dan penggunaan layanan cloud.",
        interpreterId: null,
        interpreterStatus: false,
      },

      // Chapter 38: Introduction to Web Development
      {
        id: 75,
        sort: 1,
        chapterId: 38,
        contentTitle: "What is Web Development?",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 300,
        teks: "Video ini memberikan pengantar tentang pengembangan web, menjelaskan perbedaan antara frontend, backend, dan full stack development.",
        interpreterId: null,
        interpreterStatus: false,
      },
      {
        id: 76,
        sort: 2,
        chapterId: 38,
        contentTitle: "Web Development Technologies",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 350,
        teks: "Dalam video ini, Anda akan belajar tentang berbagai teknologi yang digunakan dalam pengembangan web, termasuk HTML, CSS, dan JavaScript.",
        interpreterId: null,
        interpreterStatus: false,
      },

      // Chapter 39: HTML Basics
      {
        id: 77,
        sort: 1,
        chapterId: 39,
        contentTitle: "Understanding HTML",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 300,
        teks: "Video ini menjelaskan dasar-dasar HTML, termasuk elemen, tag, dan atribut. Anda akan belajar cara membangun struktur dasar halaman web.",
        interpreterId: null,
        interpreterStatus: false,
      },
      {
        id: 78,
        sort: 2,
        chapterId: 39,
        contentTitle: "Creating Your First HTML Page",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 350,
        teks: "Di sini, Anda akan membuat halaman HTML pertama Anda, lengkap dengan judul, paragraf, dan daftar. Video ini memberikan panduan langkah demi langkah.",
        interpreterId: null,
        interpreterStatus: false,
      },

      // Chapter 40: CSS Basics
      {
        id: 79,
        sort: 1,
        chapterId: 40,
        contentTitle: "What is CSS?",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 300,
        teks: "Video ini memperkenalkan CSS, menjelaskan fungsinya dalam desain halaman web dan cara mengatur gaya elemen HTML.",
        interpreterId: null,
        interpreterStatus: false,
      },
      {
        id: 80,
        sort: 2,
        chapterId: 40,
        contentTitle: "Styling Your HTML Page",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 350,
        teks: "Di sini, Anda akan belajar cara menerapkan CSS untuk memberikan gaya pada halaman HTML Anda. Anda akan belajar tentang selektor, warna, dan ukuran font.",
        interpreterId: null,
        interpreterStatus: false,
      },

      // Chapter 41: JavaScript Basics
      {
        id: 81,
        sort: 1,
        chapterId: 41,
        contentTitle: "Understanding JavaScript",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 300,
        teks: "Video ini memberikan pengantar tentang JavaScript, menjelaskan perannya sebagai bahasa pemrograman di web dan cara menambahkannya ke halaman HTML.",
        interpreterId: null,
        interpreterStatus: false,
      },
      {
        id: 82,
        sort: 2,
        chapterId: 41,
        contentTitle: "Basic JavaScript Syntax",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 350,
        teks: "Dalam video ini, Anda akan belajar tentang sintaks dasar JavaScript, termasuk variabel, tipe data, dan operator. Anda akan melihat cara menulis skrip JavaScript sederhana.",
        interpreterId: null,
        interpreterStatus: false,
      },

      // Chapter 42: DOM Manipulation
      {
        id: 83,
        sort: 1,
        chapterId: 42,
        contentTitle: "What is the DOM?",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 300,
        teks: "Video ini menjelaskan apa itu Document Object Model (DOM) dan bagaimana JavaScript dapat digunakan untuk berinteraksi dengan elemen di halaman web.",
        interpreterId: null,
        interpreterStatus: false,
      },
      {
        id: 84,
        sort: 2,
        chapterId: 42,
        contentTitle: "Manipulating the DOM with JavaScript",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 350,
        teks: "Di sini, Anda akan belajar cara menggunakan JavaScript untuk menambahkan, menghapus, dan mengubah elemen di halaman web dengan DOM manipulation.",
        interpreterId: null,
        interpreterStatus: false,
      },

      // Chapter 43: Introduction to Frameworks
      {
        id: 85,
        sort: 1,
        chapterId: 43,
        contentTitle: "What are Web Frameworks?",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 300,
        teks: "Video ini memberikan pengantar tentang framework web, menjelaskan keuntungan dan perbedaan antara framework frontend dan backend.",
        interpreterId: null,
        interpreterStatus: false,
      },
      {
        id: 86,
        sort: 2,
        chapterId: 43,
        contentTitle: "Popular Web Frameworks",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 350,
        teks: "Dalam video ini, berbagai framework web populer seperti React, Angular, dan Vue.js dibahas. Anda akan memahami bagaimana setiap framework bekerja dan kapan menggunakannya.",
        interpreterId: null,
        interpreterStatus: false,
      },

      // Chapter 44: Introduction to APIs
      {
        id: 87,
        sort: 1,
        chapterId: 44,
        contentTitle: "What are APIs?",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 300,
        teks: "Video ini menjelaskan apa itu Application Programming Interface (API) dan bagaimana mereka digunakan untuk memungkinkan komunikasi antara aplikasi.",
        interpreterId: null,
        interpreterStatus: false,
      },
      {
        id: 88,
        sort: 2,
        chapterId: 44,
        contentTitle: "Using APIs in Web Development",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 350,
        teks: "Di sini, Anda akan belajar cara menggunakan API dalam pengembangan web. Contoh penggunaan API publik dan cara mengaksesnya menggunakan JavaScript dijelaskan.",
        interpreterId: null,
        interpreterStatus: false,
      },

      // Chapter 45: Responsive Web Design
      {
        id: 89,
        sort: 1,
        chapterId: 45,
        contentTitle: "What is Responsive Design?",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 300,
        teks: "Video ini membahas konsep desain responsif dan mengapa penting untuk menciptakan pengalaman pengguna yang baik di berbagai perangkat.",
        interpreterId: null,
        interpreterStatus: false,
      },
      {
        id: 90,
        sort: 2,
        chapterId: 45,
        contentTitle: "Media Queries in CSS",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 350,
        teks: "Di sini, Anda akan belajar cara menggunakan media queries untuk menerapkan gaya yang berbeda berdasarkan ukuran layar. Contoh penerapan media queries di CSS juga diberikan.",
        interpreterId: null,
        interpreterStatus: false,
      },

      // Chapter 46: Version Control with Git
      {
        id: 91,
        sort: 1,
        chapterId: 46,
        contentTitle: "Introduction to Git",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 300,
        teks: "Video ini memberikan pengantar tentang Git, alat kontrol versi yang digunakan untuk melacak perubahan dalam kode. Anda akan belajar mengapa Git penting dalam pengembangan perangkat lunak.",
        interpreterId: null,
        interpreterStatus: false,
      },
      {
        id: 92,
        sort: 2,
        chapterId: 46,
        contentTitle: "Basic Git Commands",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 350,
        teks: "Di sini, Anda akan belajar tentang perintah dasar Git, termasuk git init, git add, git commit, dan git push. Video ini memberikan panduan langkah demi langkah.",
        interpreterId: null,
        interpreterStatus: false,
      },

      // Chapter 47: Introduction to Databases
      {
        id: 93,
        sort: 1,
        chapterId: 47,
        contentTitle: "What is a Database?",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 300,
        teks: "Video ini menjelaskan apa itu database dan mengapa mereka digunakan untuk menyimpan dan mengelola data. Anda akan belajar tentang perbedaan antara database relasional dan non-relasional.",
        interpreterId: null,
        interpreterStatus: false,
      },
      {
        id: 94,
        sort: 2,
        chapterId: 47,
        contentTitle: "Database Management Systems",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 350,
        teks: "Dalam video ini, berbagai sistem manajemen database (DBMS) seperti MySQL, PostgreSQL, dan MongoDB dibahas. Anda akan memahami kapan menggunakan masing-masing DBMS.",
        interpreterId: null,
        interpreterStatus: false,
      },

      // Chapter 48: SQL Basics
      {
        id: 95,
        sort: 1,
        chapterId: 48,
        contentTitle: "Introduction to SQL",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 300,
        teks: "Video ini memberikan pengantar tentang Structured Query Language (SQL) dan bagaimana ia digunakan untuk berinteraksi dengan database relasional.",
        interpreterId: null,
        interpreterStatus: false,
      },
      {
        id: 96,
        sort: 2,
        chapterId: 48,
        contentTitle: "Basic SQL Commands",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 350,
        teks: "Di sini, Anda akan belajar tentang perintah SQL dasar, termasuk SELECT, INSERT, UPDATE, dan DELETE. Video ini memberikan contoh nyata untuk setiap perintah.",
        interpreterId: null,
        interpreterStatus: false,
      },

      // Chapter 49: Data Modeling
      {
        id: 97,
        sort: 1,
        chapterId: 49,
        contentTitle: "Understanding Data Models",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 300,
        teks: "Video ini menjelaskan konsep model data dan bagaimana model data membantu dalam merancang database. Anda akan belajar tentang entity-relationship (ER) model.",
        interpreterId: null,
        interpreterStatus: false,
      },
      {
        id: 98,
        sort: 2,
        chapterId: 49,
        contentTitle: "Creating ER Diagrams",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 350,
        teks: "Di sini, Anda akan belajar cara membuat diagram ER untuk merancang struktur database. Video ini memberikan panduan langkah demi langkah.",
        interpreterId: null,
        interpreterStatus: false,
      },

      // Chapter 50: NoSQL Databases
      {
        id: 99,
        sort: 1,
        chapterId: 50,
        contentTitle: "What are NoSQL Databases?",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 300,
        teks: "Video ini memberikan pengantar tentang database NoSQL dan bagaimana mereka berbeda dari database relasional. Anda akan belajar tentang jenis-jenis NoSQL databases.",
        interpreterId: null,
        interpreterStatus: false,
      },
      {
        id: 100,
        sort: 2,
        chapterId: 50,
        contentTitle: "When to Use NoSQL",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 350,
        teks: "Di sini, Anda akan belajar kapan sebaiknya menggunakan database NoSQL. Contoh kasus penggunaan dan kelebihan NoSQL dibandingkan database relasional dibahas.",
        interpreterId: null,
        interpreterStatus: false,
      },

      // Chapter 51: Introduction to Data Science
      {
        id: 101,
        sort: 1,
        chapterId: 51,
        contentTitle: "What is Data Science?",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 300,
        teks: "Video ini memberikan pengantar tentang data science, menjelaskan apa itu data science dan bagaimana cara kerjanya. Anda juga akan belajar tentang keterampilan yang dibutuhkan untuk menjadi seorang data scientist.",
        interpreterId: null,
        interpreterStatus: false,
      },
      {
        id: 102,
        sort: 2,
        chapterId: 51,
        contentTitle: "The Data Science Process",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 350,
        teks: "Dalam video ini, Anda akan mempelajari proses data science dari awal hingga akhir, mulai dari pengumpulan data hingga analisis dan visualisasi data.",
        interpreterId: null,
        interpreterStatus: false,
      },

      // Chapter 52: Data Visualization
      {
        id: 103,
        sort: 1,
        chapterId: 52,
        contentTitle: "Importance of Data Visualization",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 300,
        teks: "Video ini menjelaskan mengapa visualisasi data penting dalam data science. Anda akan belajar bagaimana visualisasi membantu dalam pengambilan keputusan.",
        interpreterId: null,
        interpreterStatus: false,
      },
      {
        id: 104,
        sort: 2,
        chapterId: 52,
        contentTitle: "Tools for Data Visualization",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 350,
        teks: "Di sini, Anda akan mempelajari tentang berbagai alat dan pustaka untuk visualisasi data, termasuk Matplotlib, Seaborn, dan Tableau.",
        interpreterId: null,
        interpreterStatus: false,
      },

      // Chapter 53: Introduction to Machine Learning
      {
        id: 105,
        sort: 1,
        chapterId: 53,
        contentTitle: "Machine Learning Concepts",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 300,
        teks: "Video ini menjelaskan konsep dasar machine learning, termasuk perbedaan antara supervised dan unsupervised learning.",
        interpreterId: null,
        interpreterStatus: false,
      },
      {
        id: 106,
        sort: 2,
        chapterId: 53,
        contentTitle: "Machine Learning Tools",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 350,
        teks: "Di sini, Anda akan mempelajari tentang alat dan pustaka yang digunakan dalam machine learning, seperti Scikit-learn dan TensorFlow.",
        interpreterId: null,
        interpreterStatus: false,
      },

      // Chapter 54: Machine Learning Algorithms
      {
        id: 107,
        sort: 1,
        chapterId: 54,
        contentTitle: "Overview of Algorithms",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 300,
        teks: "Video ini memberikan gambaran umum tentang berbagai algoritma machine learning, termasuk regresi, klasifikasi, dan clustering.",
        interpreterId: null,
        interpreterStatus: false,
      },
      {
        id: 108,
        sort: 2,
        chapterId: 54,
        contentTitle: "Selecting the Right Algorithm",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 350,
        teks: "Dalam video ini, Anda akan belajar cara memilih algoritma yang tepat untuk masalah yang dihadapi, serta faktor-faktor yang perlu dipertimbangkan.",
        interpreterId: null,
        interpreterStatus: false,
      },

      // Chapter 55: Final Project
      {
        id: 109,
        sort: 1,
        chapterId: 55,
        contentTitle: "Building Your Final Project",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 300,
        teks: "Video ini memberikan panduan tentang cara membangun proyek akhir Anda, menggabungkan semua keterampilan yang telah Anda pelajari.",
        interpreterId: null,
        interpreterStatus: false,
      },
      {
        id: 110,
        sort: 2,
        chapterId: 55,
        contentTitle: "Presenting Your Project",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 350,
        teks: "Di sini, Anda akan belajar cara menyajikan proyek Anda secara efektif, termasuk cara menyiapkan slide dan berbicara di depan umum.",
        interpreterId: null,
        interpreterStatus: false,
      },
      // Chapter 56: Career Opportunities in Tech
      {
        id: 111,
        sort: 1,
        chapterId: 56,
        contentTitle: "Tech Career Paths",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 300,
        teks: "Video ini menjelaskan berbagai jalur karir dalam industri teknologi, mulai dari pengembangan perangkat lunak hingga data science. Anda akan belajar tentang keterampilan dan pendidikan yang dibutuhkan untuk setiap jalur.",
        interpreterId: null,
        interpreterStatus: false,
      },
      {
        id: 112,
        sort: 2,
        chapterId: 56,
        contentTitle: "Building a Strong Portfolio",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 350,
        teks: "Di sini, Anda akan belajar cara membangun portofolio yang kuat untuk menarik perhatian perekrut. Video ini mencakup contoh proyek yang bisa Anda tambahkan ke portofolio Anda.",
        interpreterId: null,
        interpreterStatus: false,
      },

      // Chapter 57: Networking in Tech
      {
        id: 113,
        sort: 1,
        chapterId: 57,
        contentTitle: "The Importance of Networking",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 300,
        teks: "Video ini membahas pentingnya membangun jaringan profesional dalam industri teknologi. Anda akan belajar cara menemukan dan terhubung dengan profesional lainnya.",
        interpreterId: null,
        interpreterStatus: false,
      },
      {
        id: 114,
        sort: 2,
        chapterId: 57,
        contentTitle: "Effective Networking Strategies",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 350,
        teks: "Di sini, Anda akan mempelajari strategi efektif untuk membangun jaringan. Video ini mencakup cara menghadiri acara, menggunakan media sosial, dan menjalin hubungan yang bermanfaat.",
        interpreterId: null,
        interpreterStatus: false,
      },

      // Chapter 58: Continuing Education
      {
        id: 115,
        sort: 1,
        chapterId: 58,
        contentTitle: "The Importance of Lifelong Learning",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 300,
        teks: "Video ini menjelaskan pentingnya pendidikan berkelanjutan dalam teknologi. Anda akan belajar tentang cara tetap relevan di industri yang selalu berubah ini.",
        interpreterId: null,
        interpreterStatus: false,
      },
      {
        id: 116,
        sort: 2,
        chapterId: 58,
        contentTitle: "Online Learning Resources",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 350,
        teks: "Di sini, Anda akan menemukan berbagai sumber daya belajar online, termasuk kursus dan platform yang menawarkan pelatihan dalam berbagai bidang teknologi.",
        interpreterId: null,
        interpreterStatus: false,
      },

      // Chapter 59: Preparing for Job Interviews
      {
        id: 117,
        sort: 1,
        chapterId: 59,
        contentTitle: "Job Interview Basics",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 300,
        teks: "Video ini memberikan panduan dasar untuk persiapan wawancara kerja. Anda akan belajar tentang jenis pertanyaan yang sering ditanyakan dan cara menjawabnya dengan percaya diri.",
        interpreterId: null,
        interpreterStatus: false,
      },
      {
        id: 118,
        sort: 2,
        chapterId: 59,
        contentTitle: "Technical Interview Tips",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 350,
        teks: "Di sini, Anda akan belajar tips untuk menghadapi wawancara teknis. Video ini mencakup cara mempersiapkan diri dan strategi untuk mengatasi tantangan yang mungkin muncul.",
        interpreterId: null,
        interpreterStatus: false,
      },

      // Chapter 60: Conclusion
      {
        id: 119,
        sort: 1,
        chapterId: 60,
        contentTitle: "Course Summary",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 300,
        teks: "Video ini memberikan ringkasan kursus secara keseluruhan, menyoroti keterampilan yang telah dipelajari dan bagaimana Anda dapat menerapkannya dalam karir Anda.",
        interpreterId: null,
        interpreterStatus: false,
      },
      {
        id: 120,
        sort: 2,
        chapterId: 60,
        contentTitle: "Next Steps in Your Learning Journey",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 350,
        teks: "Di sini, Anda akan mendapatkan saran untuk langkah-langkah selanjutnya dalam perjalanan pembelajaran Anda. Video ini mencakup rekomendasi untuk kursus lanjutan dan pengembangan diri.",
        interpreterId: null,
        interpreterStatus: false,
      },

      // Chapter 61: Introduction to Cloud Computing
      {
        id: 121,
        sort: 1,
        chapterId: 61,
        contentTitle: "What is Cloud Computing?",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 300,
        teks: "Video ini memberikan pengantar tentang cloud computing, menjelaskan apa itu dan bagaimana ia mengubah cara kita menyimpan dan mengelola data.",
        interpreterId: null,
        interpreterStatus: false,
      },
      {
        id: 122,
        sort: 2,
        chapterId: 61,
        contentTitle: "Types of Cloud Services",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 350,
        teks: "Di sini, Anda akan belajar tentang berbagai jenis layanan cloud, termasuk IaaS, PaaS, dan SaaS. Video ini menjelaskan bagaimana masing-masing layanan digunakan dalam pengembangan perangkat lunak.",
        interpreterId: null,
        interpreterStatus: false,
      },

      // Chapter 62: Cloud Deployment Models
      {
        id: 123,
        sort: 1,
        chapterId: 62,
        contentTitle: "Public vs. Private Cloud",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 300,
        teks: "Video ini menjelaskan perbedaan antara cloud publik dan privat. Anda akan belajar kapan dan mengapa menggunakan masing-masing model cloud.",
        interpreterId: null,
        interpreterStatus: false,
      },
      {
        id: 124,
        sort: 2,
        chapterId: 62,
        contentTitle: "Hybrid Cloud Solutions",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 350,
        teks: "Di sini, Anda akan mempelajari tentang solusi cloud hibrid dan bagaimana mereka menggabungkan keuntungan dari cloud publik dan privat.",
        interpreterId: null,
        interpreterStatus: false,
      },

      // Chapter 63: Cloud Security
      {
        id: 125,
        sort: 1,
        chapterId: 63,
        contentTitle: "Understanding Cloud Security",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 300,
        teks: "Video ini membahas pentingnya keamanan dalam cloud computing. Anda akan belajar tentang tantangan keamanan yang dihadapi oleh organisasi saat menggunakan layanan cloud.",
        interpreterId: null,
        interpreterStatus: false,
      },
      {
        id: 126,
        sort: 2,
        chapterId: 63,
        contentTitle: "Best Practices for Cloud Security",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 350,
        teks: "Di sini, Anda akan menemukan praktik terbaik untuk menjaga keamanan data di cloud. Video ini mencakup langkah-langkah yang harus diambil untuk melindungi informasi sensitif.",
        interpreterId: null,
        interpreterStatus: false,
      },

      // Chapter 64: Introduction to DevOps
      {
        id: 127,
        sort: 1,
        chapterId: 64,
        contentTitle: "What is DevOps?",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 300,
        teks: "Video ini memberikan pengantar tentang DevOps, menjelaskan prinsip-prinsip dan tujuan dari pendekatan ini dalam pengembangan perangkat lunak.",
        interpreterId: null,
        interpreterStatus: false,
      },
      {
        id: 128,
        sort: 2,
        chapterId: 64,
        contentTitle: "DevOps Practices and Tools",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 350,
        teks: "Di sini, Anda akan mempelajari praktik dan alat yang umum digunakan dalam DevOps, termasuk CI/CD dan pengelolaan infrastruktur sebagai kode.",
        interpreterId: null,
        interpreterStatus: false,
      },

      // Chapter 65: Agile Methodology
      {
        id: 129,
        sort: 1,
        chapterId: 65,
        contentTitle: "Understanding Agile Methodology",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 300,
        teks: "Video ini menjelaskan metodologi Agile, termasuk prinsip-prinsip dan proses pengembangannya. Anda akan belajar mengapa Agile menjadi populer dalam proyek perangkat lunak.",
        interpreterId: null,
        interpreterStatus: false,
      },
      {
        id: 130,
        sort: 2,
        chapterId: 65,
        contentTitle: "Implementing Agile in Projects",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 350,
        teks: "Di sini, Anda akan mempelajari cara menerapkan metodologi Agile dalam proyek Anda, termasuk bagaimana membentuk tim dan mengelola backlog.",
        interpreterId: null,
        interpreterStatus: false,
      },

      // Chapter 66: Conclusion of the Course
      {
        id: 131,
        sort: 1,
        chapterId: 66,
        contentTitle: "Final Thoughts",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 300,
        teks: "Video ini menyimpulkan kursus dengan beberapa pemikiran akhir. Anda akan mendapatkan wawasan tentang bagaimana menggunakan keterampilan yang telah Anda pelajari untuk mencapai tujuan karir Anda.",
        interpreterId: null,
        interpreterStatus: false,
      },
      {
        id: 132,
        sort: 2,
        chapterId: 66,
        contentTitle: "Future Learning Opportunities",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 350,
        teks: "Di sini, Anda akan mendapatkan informasi tentang peluang belajar di masa depan, termasuk kursus lanjutan dan sumber daya untuk pengembangan profesional.",
        interpreterId: null,
        interpreterStatus: false,
      },

      // Chapter 67: Additional Resources
      {
        id: 133,
        sort: 1,
        chapterId: 67,
        contentTitle: "Recommended Books and Articles",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 300,
        teks: "Video ini memberikan rekomendasi buku dan artikel yang bermanfaat untuk memperdalam pemahaman Anda tentang topik-topik yang telah dibahas dalam kursus.",
        interpreterId: null,
        interpreterStatus: false,
      },
      {
        id: 134,
        sort: 2,
        chapterId: 67,
        contentTitle: "Online Communities and Forums",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 350,
        teks: "Di sini, Anda akan menemukan komunitas online dan forum di mana Anda dapat terhubung dengan orang lain yang memiliki minat yang sama dan berbagi pengetahuan.",
        interpreterId: null,
        interpreterStatus: false,
      },

      // Chapter 68: Feedback and Course Evaluation
      {
        id: 135,
        sort: 1,
        chapterId: 68,
        contentTitle: "Giving Feedback",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 300,
        teks: "Video ini menjelaskan bagaimana memberikan umpan balik yang konstruktif untuk kursus ini. Umpan balik Anda sangat berharga untuk perbaikan di masa depan.",
        interpreterId: null,
        interpreterStatus: false,
      },
      {
        id: 136,
        sort: 2,
        chapterId: 68,
        contentTitle: "Course Evaluation Process",
        contentUrl: "https://www.youtube.com/watch?v=ckEa0SGYgFI",
        duration: 350,
        teks: "Di sini, Anda akan mempelajari tentang proses evaluasi kursus dan bagaimana kontribusi Anda dapat membantu meningkatkan pengalaman belajar bagi peserta di masa depan.",
        interpreterId: null,
        interpreterStatus: false,
      },
    ],
  });
};
